set -s focus-events on

set -g  base-index 1
set -g  display-time 2500
set -g  prefix C-a
set -g  renumber-windows on
set -g  set-titles on
set -g  status-position bottom
set -ga update-environment NIRI_SOCKET
set -ga update-environment SWAYSOCK

set -gw allow-rename on
set -gw mode-keys vi
set -gw pane-border-status off
set -gw pane-base-index 1
set -gw main-pane-width 83

unbind C-b
bind   C-a send-prefix

# Config/helpers
bind R source ~/.config/tmux/tmux.conf \; display 'Config reloaded'
bind q display-panes -d 0
bind : command-prompt -p '>'

bind -N 'Reload config' R
bind -N 'Display pane numbers to select' q
bind -N 'Open command prompt' :

# Window splitting
bind  %  splitw -c '#{pane_current_path}' -h \; refresh -S
bind '"' splitw -c '#{pane_current_path}' -v \; refresh -S
bind '\' splitw -c '#{pane_current_path}' -vl 10 \; refresh -S

# Window split while maintaining main layout
bind / {
    splitw -c '#{pane_current_path}' -h
    selectl main-vertical
    refresh -S
}

bind -N 'Split window maintaining main-vertical' /
bind -N 'Split window horizontally' %
bind -N 'Split window vertically'  '"'
bind -N 'Split window vertically (small)' '\'

# Window creating
bind c neww -c '#{pane_current_path}' -a \; refresh -S
bind C neww -c '#{pane_current_path}' -b \; refresh -S

bind -N 'Create new window (after current)' c
bind -N 'Create new window (before current)' C

# Pane selection
bind -r h select-pane -L \; refresh -S
bind -r j select-pane -D \; refresh -S
bind -r k select-pane -U \; refresh -S
bind -r l select-pane -R \; refresh -S
bind -r C-h select-pane -L \; refresh -S
bind -r C-j select-pane -D \; refresh -S
bind -r C-k select-pane -U \; refresh -S
bind -r C-l select-pane -R \; refresh -S

bind -N 'Select left pane' h
bind -N 'Select below pane' j
bind -N 'Select above pane' k
bind -N 'Select right pane' l

# Pane resizing
bind -r M-h resize-pane -L
bind -r M-j resize-pane -D
bind -r M-k resize-pane -U
bind -r M-l resize-pane -R

bind -N 'Resize pane left' M-h
bind -N 'Resize pane right' M-j
bind -N 'Resize pane up' M-k
bind -N 'Resize pane down' M-l

source ~/.config/tmux/conf.d/*.conf
set-hook -g session-created 'source -Fq ~/.config/tmux/session/#S.conf'
