# vim: ft=tmux

set -g cursor-style blinking-block
set -g status-style bg=gray,fg=black

set -g status-left-length 8
set -g status-left-style default
set -g status-left ' #{session_name} '

set -gw window-status-separator ''
set -gw window-status-format ' #I #W#F '
set -gw window-status-current-format ' #I #W#F '
set -gw window-status-current-style 'bg=terminal fg=green'

set -g status-right-length 50
set -g status-right ' '

set -ga status-right \
    '#{?#{!=:#{client_key_table},root}, #{client_key_table} }'

# Battery status
set -gqo @s_bat 0
set -gq  @s_bat_path  '/sys/class/power_supply'
set -ga  status-right '#(head -c1 #{@s_bat_path}/BAT#{@s_bat}/status)'
set -ga  status-right '#(cat #{@s_bat_path}/BAT#{@s_bat}/capacity)%'
set -ga  status-right ' | '

# CPU temp
set -gqo @s_tz 0
set -gq  @s_tz_path '/sys/class/thermal'
set -ga status-right '#(head -c2 #{@s_tz_path}/thermal_zone#{@s_tz}/temp)'
set -ga status-right 'C | '

# Date
set -gqo @s_date_fmt '%d/%m %H:%M'
set -ga status-right '#(date "+#{@s_date_fmt}")'
set -ga status-right ' '
