# -*- conf -*-

font=iosevka:pixelsize=19:style=extended
line-height=28px
pad=8x8
include=~/.config/foot/theme.ini

[cursor]
style=block
blink=yes

[csd]
preferred=none

[scrollback]
lines=40160

[colors-dark]
alpha=0.85

# vim: ft=dosini
